name: publish to nuget
on:
  push:
    branches:
      - main
      - v*
jobs:
  publish:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check version equality
        run: bash scripts/check-version-equality.sh

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |-
            8.x
            9.x

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: |
          dotnet build src/WebJobs.Extensions.IBMMQ/WebJobs.Extensions.IBMMQ.csproj --configuration Release --no-restore
          dotnet build src/Worker.Extensions.IBMMQ/Worker.Extensions.IBMMQ.csproj --configuration Release --no-restore
        
      - name: Pack
        run: |
          dotnet pack src/WebJobs.Extensions.IBMMQ/WebJobs.Extensions.IBMMQ.csproj --configuration Release --no-build -o .
          dotnet pack src/Worker.Extensions.IBMMQ/Worker.Extensions.IBMMQ.csproj --configuration Release --no-build -o .
        
      - name: Publish
        run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}